Qisra/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include,re_path
from django.http import HttpResponse
from django.conf.urls.static import static 
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('main.urls')),
    path('testcase/',include('testcase.urls')),
    path("testplan/",include('testplan.urls')),
    path("project/",include('project.urls')),
    path("vister/",include('signup_app.urls')),
] 

urlpatterns+= static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.contrib.auth.decorators import login_required
from . import views
urlpatterns = [
    re_path(r"^base_navbar/$", views.base_navbar),
    path("", login_required(views.DashboardView.as_view()),name="Dashboard"),
    path(r"profile_view/",views.profile_view ,name="profile_view"),
    path(r"div_table/",views.test_div ,name="div_table"),
]

testcase/urls.py
from django.contrib import admin
from django.urls import re_path,path
from . import views

urlpatterns = [
    re_path(r"^new_test1/$", views.TestcaseNew_test, name="testcases-create-test"),
    re_path(r"^new_tag/$", views.add_tag, name="new_tag"),
    re_path(r"^(?P<pk>\d+)/teststep/$", views.TestStepView, name="teststep"),
]

testcase/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from simple_history.models import HistoricalRecords


'''
teststep class models
'''


class Tag(models.Model):
    name = models.CharField(max_length=100, null=True)
    description = models.TextField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    creator = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    history = HistoricalRecords(cascade_delete_history=True)
    def __str__(self):
        return self.name


class Testcase(models.Model):
    name = models.CharField(max_length=500, null=True, blank=True)
    description = RichTextField()
    tag = models.ManyToManyField(Tag)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    date_modify = models.DateTimeField(auto_now=True, null=True, blank=True)
    creator = models.ForeignKey(
        User, null=True, on_delete=models.SET_NULL, related_name='Testcase_creator')
    history = HistoricalRecords(cascade_delete_history=True)

    def __str__(self):
        return self.name


class Teststep(models.Model):
    testcase = models.ForeignKey(
        Testcase, null=True, on_delete=models.CASCADE)
    number = models.IntegerField()
    description = RichTextField()
    condition = RichTextField()
    remark = RichTextField()
    history = HistoricalRecords(cascade_delete_history=True)

    def __str__(self):
        name = self.testcase.name+'-('+str(self.number)+')'
        return name


class testcase_import_excel(models.Model):
    filename = models.CharField(max_length=100, null=True, blank=True)
    file = models.FileField(upload_to='uploads/excel/')
    def __str__(self):
        return self.filename

class testcase_file(models.Model):
    testcase = models.ForeignKey(
        Testcase, null=True, on_delete=models.CASCADE)
    filename = models.CharField(max_length=100, null=True, blank=True)
    file = models.FileField(upload_to='uploads/testcase_excel/')
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    uploader = models.ForeignKey(
        User, null=True, on_delete=models.SET_NULL, related_name='testcase_file_uploader')
    def __str__(self):
        return self.filename

        
class teststep_file(models.Model):
    teststep = models.ForeignKey(
        Teststep, null=True, on_delete=models.CASCADE)
    filename = models.CharField(max_length=100, null=True, blank=True)
    file = models.FileField(upload_to='uploads/teststep_excel/')
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    uploader = models.ForeignKey(
        User, null=True, on_delete=models.SET_NULL, related_name='teststep_file_uploader')
    def __str__(self):
        return self.filename

testcase/forms.py
# -*- coding: utf-8 -*-
from django import forms
from testcase.models import (
    Testcase,
    Teststep,
    testcase_import_excel,
    testcase_file
)
from ckeditor.widgets import CKEditorWidget

'''
new Testcase search
'''
class SearchCaseFormTest(forms.ModelForm):
    class Meta:
        model = Testcase
        fields = ['name']
        
class TestCasetestform(forms.ModelForm):
    class Meta:
        model = Testcase    
        fields = ['name','tag','description']   
        
class Teststepform(forms.ModelForm):
    class Meta:
        model = Teststep
        fields = ['description','condition','remark']

class save_excelform(forms.ModelForm):
    class Meta:
        model = testcase_import_excel
        fields = ['filename','file']

class testcase_fileForm(forms.ModelForm):
    class Meta:
        model = testcase_file
        fields = '__all__'

testcase/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
import pandas as pd
from django.forms import inlineformset_factory
from testcase.forms import (
    Teststepform,
    TestCasetestform,
    save_excelform,
)
from project.models import Project
from testcase.decorators import allowed_user
import openpyxl
from django.views.generic.base import TemplateView, View
from testcase.openpyxl_image_loader import SheetImageLoaderlist
from io import BytesIO
import base64
from testcase.models import (
    Teststep,
    Testcase,
    Tag,testcase_file,teststep_file,
    testcase_import_excel)

from testplan.models import Testrun


import re
from difflib import SequenceMatcher
import json
import ast
from django.contrib.auth.models import User
from django.core.files.base import File
import os
from datetime import datetime as dt2
import datetime as dt
import csv
from django.contrib.auth.decorators import login_required
from signup_app.decorators import allowed_user
from simple_history.utils import update_change_reason
import time
# clone method
from main.clone_method import Clone_Models

'''
import excel
還沒有設定權限
'''
@login_required
def add_tag(request):
    bool_exists = False
    new_tag_name = request.GET['tag_name']
    try:
        Tag.objects.get(name=new_tag_name)
        bool_exists = True
    except:
        new_tag = Tag.objects.create(name=new_tag_name)
        return JsonResponse({'name':new_tag_name,'id':str(new_tag.id),'status':'pass'})
    if bool_exists == True:
        return JsonResponse({'name':new_tag_name,'status':'fail'})

def str_remove(item):
    item = str(item)
    item2 = item.replace('[', '')
    item2 = item2.replace(']', '')
    return item2

def im_2_b64(image):
    buff = BytesIO()
    image.save(buff, format="PNG")
    img_str = base64.b64encode(buff.getvalue())
    return img_str


'''
比較字的相似度
'''


def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

def get_history(history_model):
    '''
    history_model (Model.class): model.history.all()
    '''
    history_dict = {}
    for h in history_model:
        try:
            history_reason = (h.history_change_reason).split('||')
            count = 0
            history_reason_list_all = []
            history_reason_list = []
            for reason_item in history_reason:
                if count < 4:
                    history_reason_list.append(reason_item)
                else:
                    history_reason_list_all.append(history_reason_list)
                    history_reason_list = [reason_item]
                    count = 0
                count += 1
            history_dict[h] = history_reason_list_all
        except Exception as e:
            pass
    return history_dict

def get_file_data(model):
    '''
    model : file model
    '''
    format_data = "%Y-%m-%d %H:%M:%S"
    file_path = model.file.path
    try:
        file_path = file_path.split('media/')[1]
    except:
        file_path = file_path.split('media\\')[1]
    filename = model.filename
    temp_time = str(model.date_created)
    temp_time = temp_time.split(' ')
    temp_date = temp_time[0]
    temp_time = (temp_time[1].split('.'))[0]
    temp_time = temp_date+' '+temp_time
    temp_time = dt2.strptime(temp_time, format_data)
    temp_time = temp_time + dt.timedelta(hours=8)
    temp_time = str(temp_time)
    return file_path,filename,temp_time



@login_required
def TestStepView(request, pk):
    testcase = Testcase.objects.get(id=pk)
    tag_object_list = testcase.tag.all()
    testcaseform = TestCasetestform()
    testcase_file_list = testcase_file.objects.filter(testcase = testcase)
    teststep = Teststep.objects.filter(testcase=testcase).order_by('number')
    teststep_orignal_id_list = []
    for item in teststep:
        teststep_orignal_id_list.append(int(item.id))
    teststepform = Teststepform()
    teststepset = inlineformset_factory(Testcase, Teststep, fields=(
        'number', 'description', 'condition', 'remark'), extra=0)
    form_teststep_list = teststepset(instance=testcase,queryset=Teststep.objects.order_by('number'))
    current_user = request.user   
    # teststep file
    teststep_dict = {}
    for item in teststep:
        teststep_dict[item] = teststep_file.objects.filter(teststep=item)
    # get history dict
    testcase_history_model = testcase.history.all()
    history_dict = get_history(testcase_history_model)
    # reason_history
    temp_blank = ''
    # detect testcase in any testplan-group testrun or not 
    testrun_count = Testrun.objects.filter(testcase = testcase).count()
    if 'save_teststep' in request.POST:
        '''
        teststep update
        '''
        change_reason = ''
        for item in request.POST:
            if 'id_teststep_set' in item:
                item_name = item.split('-')
                item_testsstep_id = item_name[1]
                item_data = request.POST.getlist(item)
                try:
                    temp_teststep = Teststep.objects.get(id=int(item_testsstep_id))
                    temp_teststep.number = int(item_data[0])
                    temp_teststep.description = item_data[1].replace('<p></p>','')
                    temp_teststep.condition = item_data[2].replace('<p></p>','')
                    temp_teststep.remark = item_data[3].replace('<p></p>','')
                    temp_teststep.save()
                    # history
                    new_record, old_record, *_ = temp_teststep.history.all()
                    delta = new_record.diff_against(old_record)
                    for change in delta.changes:
                        if change.field != 'number':
                            if change.field == 'description':
                                title = '驗證項目'
                            elif change.field == 'condition':
                                title = '驗證條件'
                            elif change.field == 'remark':
                                title = '備註'
                            if len(change.old) > len(change.new):
                                try:
                                    res = ''.join(change.old.split(change.new))
                                except:
                                    res = change.old
                            else:
                                try:
                                    res = ''.join(change.new.split(change.old))
                                except:
                                    res = change.new
                            final_data = res.strip().replace('<br>', '').replace('<br />', '').replace(' ', '')
                            final_data = final_data.replace('<p></p>','')
                            if final_data != '':
                                change_reason += "編輯||編號{}-{}:\n||{}||{}||".format(
                                    str(item_data[0]), title, change.old, change.new)
                    teststep_orignal_id_list.remove(int(item_testsstep_id))
                except:
                    Teststep.objects.create(testcase=testcase,
                                            number= int(item_data[0]),
                                            description=item_data[1],
                                            condition=item_data[2],
                                            remark=item_data[3])
                    change_reason += "新增||編號{}:\n||{}||{}||".format(
                        str(item_data[0]), temp_blank, item_data[1])
        # print('teststep_orignal_id_list',teststep_orignal_id_list)
        for item in teststep_orignal_id_list:
            try:
                temp_teststep = Teststep.objects.get(id=item)
                change_reason += "刪除||編號{}:\n||{}||{}||".format(
                        str(temp_teststep.number), temp_teststep.description,temp_blank)
                temp_teststep.delete()
            except:
                pass
            
        testcase.save()
        if change_reason != '':
            update_change_reason(testcase, change_reason)
        teststep = Teststep.objects.filter(testcase=testcase).order_by('number')
        
        # teststep file
        teststep_dict = {}
        for item in teststep:
            teststep_dict[str(item.number)] = {
                'id':item.id,
                'description':item.description,
                'condition':item.condition,
                'remark':item.remark
            }
            temp_list = []
            for file_item in teststep_file.objects.filter(teststep=item):
                format_data = "%Y-%m-%d %H:%M:%S"
                file_path = file_item.file.path
                file_path = file_path.split('media/')[1]
                filename = file_item.filename
                temp_time = str(file_item.date_created)
                temp_time = temp_time.split(' ')
                temp_date = temp_time[0]
                temp_time = (temp_time[1].split('.'))[0]
                temp_time = temp_date+' '+temp_time
                temp_time = dt2.strptime(temp_time, format_data)
                temp_time = temp_time + dt.timedelta(hours=8)
                temp_time = str(temp_time)
                temp_list.append([filename,file_path,file_item.uploader.username,temp_time,str(file_item.id)])
            teststep_dict[str(item.number)]['filelist']= temp_list
        return JsonResponse({
            'teststep_dict':teststep_dict
        })
    elif 'save_info' in request.POST:
        detect_exist_name = False
        '''
        testcasename update
        '''
        testcasename = request.POST['testcasename']
        try:
            testcase_name_object = Testcase.objects.get(name=testcasename)
            if testcase_name_object.pk != testcase.pk:
                detect_exist_name = True
        except:
            pass
        if detect_exist_name == True:

testcase/templates/testcase/create_testcase.html
{% extends "main/base.html" %}
{% load i18n %}
{% load static %}

{% block head %}
    {{ form.media }}
    
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor.js' %}"></script>
    <script type="text/javascript"  src="{% static 'ckeditor/ckeditor/lang/en.js' %}"></script>

{% endblock %}
{% block title %}
    {% trans "New Test Case" %}
{% endblock %}

{% block contents %}    
<link rel="stylesheet" type="text/css" href="{% static 'testcase/css/create_testcase.css' %}" />  
    <div class="col-lg-12 mx-auto p-3 py-md-5">
        <form class="form-horizontal" action="{% url 'testcases-create-test' %}" method="post" id="allform">
            {% csrf_token %}
        
            <div class="form-group">
                <label class="col-md-1 col-lg-1" for="id_testcasename">{% trans "名稱" %}</label>
                <div class="col-md-3 col-lg-3 {% if form_testcase.name.errors %}has-error{% endif %}">
                    <input type="text" id="id_testcasename" name="name" class="form-control" required>
                        {{ form_testcase.name.errors }}
                </div>
                <a class="btn btn-warning" style="float: right;" data-bs-toggle="modal" href="#import_testcase_toggle" role="button">匯入Testcase</a>
                <div class="modal fade" id="import_testcase_toggle" aria-hidden="true" aria-labelledby="import_excel_label" tabindex="-1">
                    {% include "testcase/Create_testcase/import_excel_modal.html" %}
                </div>
            </div>
            <div id="error-name" style="color: red; font-size: 15px;" class="status_show_position hidden ">
                名稱不可空白
            </div>
            <div class="form-group">
                <!-- <div style="float: right;"><button id="import_testcase">test</button></div> -->
                <div class="col-1 label-shift-y" ><label for="id_tag" class="form-label">標籤</label></div>
                <select class="selectpicker" multiple data-live-search="true" name="id_tag" id="id_tag">   
                    {% for tag in tag_object %}
                        <option value="{{tag.name}}">{{tag.name}}</option>
                    {% endfor %}
                </select>
                <a class="btn" data-bs-toggle="modal" href="#tag_toggle" role="button"><img src='/static/images/journal-plus.svg'></a>
                <div class="modal fade" id="tag_toggle" aria-hidden="true" aria-labelledby="tag_toggleLabel" tabindex="-1">
                    {% include "testcase/Form_View/tag_modal.html" %}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-1 col-lg-1" for="id_text">{% trans "描述" %}</label>
                <div class="col-md-3 col-lg-5">
                    <textarea class="ckeditor" cols="80" name="content" id="content"></textarea>
                </div>
            </div>
            <hr>
            <div class="form-group">
                <div class="col-md-6 col-lg-6">
                    <h1>Teststeps:</h1>
                    
                </div>
                <div class="">
                    <button type="button" name="Save_btn" value="Save_btn" id="Save_btn" class="btn btn-success btn-md">{% trans "Save" %}</button>

                    <img src='/static/images/Ellipsis-2.4s-48px.svg' id="loading_save_testcase" class="hidden">
                    <a type="button" class="btn" style="float:right" id="fullscreen"><img src='/static/images/fullscreen.svg'></a>
                    <a type="button" class="btn hidden" style="float:right" id="smallscreen"><img src='/static/images/fullscreen-exit.svg'></a>
                </div>
            </div>
            {{teststepform.media}}
            <div class="form-group tableFixHead create_testcase_table" id="create_testcase_table">
                <table class="table table-hover table_border testcase">
                    <thead>
                        <tr class="header">
                            <th>編號</th>
                            <th>驗證項目</th>
                            <th>驗證條件</th>
                            <th>備註</th>
                        </tr>
                    </thead>
                    <tbody id="formset-teststep">
                        <tr class="hidden" id="teststep_tr_list">
                            <td id="number"></td>
                            <td id="description">{{teststepform.description}}</td required>
                            <td id="condition">{{teststepform.condition}}</td>
                            <td id="remark">
                                {{teststepform.remark}}
                            </td>
                        </tr>
                    </tbody>
                </table>
                
                <div class="col-md-1 col-lg-1">
                    <button type="button" id="add_teststepform" name="add_teststepform" value="add_teststepform" class="btn btn-info btn-md">{% trans "add Teststep" %}</button>
                </div>
                <div class="col-md-4 col-lg-4">
                </div>
            </div>
            <hr style="height:30px">
        </form>
    </div>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script> -->
    <script src="{% static 'cdn/ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js' %}"></script>
    <script src="{% static 'testcase/js/createtestcase.js' %}"></script>

    
{% endblock %}

testcase/templates/testcase/teststep_view.html
{% extends "main/base.html" %}
{% load static %}

{% load i18n %}
{% block title %}Testcase-{{testcase.name}}{% endblock %}
{% block head %}
    <script src="{% static 'ckeditor/ckeditor.js' %}"></script>
{% endblock %}
{% block contents %}       
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script> -->
    <script src="{% static 'cdn/ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js' %}"></script>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'cdn/cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css' %}" />

    <link rel="stylesheet" type="text/css" href="{% static 'testcase/css/teststep_view.css' %}" />  
    <link rel="stylesheet"  type="text/css" href="{% static 'testcase/css/info.css' %}">
    <form method="POST" action="" class="needs-validation">
        {% csrf_token %}
    <div class="col-lg-12 mx-auto p-3 py-md-5">
        <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
            <span class="fs-4" >[TEM-{{testcase.id}}] <span id="testcase_title">{{testcase.name}}</span></span>
            {% if creator_bool == True %}
                <div class="dropdown text-end" id="dropdown_three_dot">
                    <a href="#" class="btn" data-bs-toggle="dropdown" id="dropdownedit" aria-expanded="false"><img src='/static/images/three-dots-vertical.svg'></a></li>
                    <ul class="dropdown-menu text-small" aria-labelledby="dropdownedit">
                        <div id="clone_div">
                            <li><button class="dropdown-item btn" type="submit" id="clone" name="clone"><img src='/static/images/clipboard-plus-fill.svg'> CLONE</button></li>
                        </div>
                        {% if testrun_count > 0 %}
                            <a class="btn dropdown-item hidden" data-bs-toggle="modal" href="#delete_toggle" role="button"><img src='/static/images/trash3-fill.svg'> DELETE</a>
                        {% else %}
                            <li><hr class="dropdown-divider"></li>
                            <a class="btn dropdown-item" data-bs-toggle="modal" href="#delete_toggle" role="button"><img src='/static/images/trash3-fill.svg'> DELETE</a>
                        {% endif %}
                    </ul>
                </div>
            {% else %}
                <div class="dropdown text-end hidden" id="dropdown_three_dot">
                    <a href="#" class="btn" data-bs-toggle="dropdown" id="dropdownedit" aria-expanded="false"><img src='/static/images/three-dots-vertical.svg'></a></li>
                    <ul class="dropdown-menu text-small" aria-labelledby="dropdownedit">
                        <div id="clone_div">
                            <li><button class="dropdown-item btn" type="submit" id="clone" name="clone"><img src='/static/images/clipboard-plus-fill.svg'> CLONE</button></li>
                            <li><hr class="dropdown-divider"></li>
                        </div>
                        <a class="btn dropdown-item" data-bs-toggle="modal" href="#delete_toggle" role="button"><img src='/static/images/trash3-fill.svg'> DELETE</a>
                    </ul>
                </div> 
            {% endif %}
            <div class="modal fade modal-delete" id="delete_toggle" aria-hidden="true" aria-labelledby="delete_toggleLabel" tabindex="-1">
                {% include "testcase/Testcase_view/delete_info.html" %}
            </div>
        </header>
    <main>
        <p>
            <h5>議題詳情
                <span style="padding-left: 30px;" class="" id="edit-save-div-info">
                    {% if creator_bool == True %}
                        <button type="button" class="btn btn-md cleared" onclick="return _Edit_info(this)" id="Edit_info_btn"><i class="fa-solid fa-pen-to-square"></i></button>
                    {% else %}
                        <button type="button" class="btn btn-md cleared hidden" onclick="return _Edit_info(this)" id="Edit_info_btn"><i class="fa-solid fa-pen-to-square"></i></button>
                    {% endif %}
                    <button type="button" class="btn btn-sm btn-success hidden" onclick="return _Save_info(this)" id="Save_info_btn">儲存</button>
                    <button type="button" class="btn btn-sm btn-warning hidden" onclick="return _Cancel_info(this)" id="Cancel_info_btn">取消</button>
                </span>
                <img src='/static/images/Ellipsis-2.4s-48px.svg' id="loading_save_info" class="hidden">
            </h5>
            <button class="fa-solid fa-sort-down dropdown_btn" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="true" aria-controls="collapseExample"
            aria-label="議題詳情" style="border: 0; transform: rotate(0deg);transition:0.5s" id="dropdown_btn1" ></button> 
        </p>
        <div class="row g-5 collapse show" id="collapseExample">
            {% include "testcase/Testcase_view/info.html" %}
            <div class="col-md-2" id="first_box_info_2"> 
            </div>
            <div class="col-md-1" id="first_box_info_3">
            </div>
        </div>
    </main>
    <br>
    <main>
        <h5>描述
            <span style="padding-left: 20px;" class="" id="second-box-edit-save_div">
                {% if creator_bool == True %}
                    <button type="button" class="btn btn-md cleared" onclick="return _Edit_context(this)" id="Edit_context_btn"><i class="fa-solid fa-pen-to-square"></i></button>
                {% else %}
                    <button type="button" class="btn btn-md cleared hidden" onclick="return _Edit_context(this)" id="Edit_context_btn"><i class="fa-solid fa-pen-to-square"></i></button>
                {% endif %}
                <button type="button" class="btn btn-sm btn-success hidden" onclick="return _Save_context(this)" id="Save_context_btn">儲存</button>
                <button type="button" class="btn btn-sm btn-warning hidden" onclick="return _Cancel_context(this)" id="Cancel_context_btn">取消</button>
            </span>
            <img src='/static/images/Ellipsis-2.4s-48px.svg' id="loading_save_context" class="hidden">
        </h5>
        <button class="fa-solid fa-sort-down dropdown_btn" type="button" data-bs-toggle="collapse" data-bs-target="#second-box-data" aria-expanded="true" aria-controls="second-box-data"
        aria-label="second-box-data" style="border: 0; transform: rotate(0deg);" id="dropdown_btn2" ></button> 
        <div class="row g-5 collapse show" id="second-box-data">
            {% include "testcase/Testcase_view/context.html" %}
        </div>
    </main>
    <main>
        <p>
            <h5>Teststep ({{teststep_dict|length}})
                <span style="padding-left: 20px;" class="" id="edit-save-div-teststep">
                    {% if creator_bool == True %}
                    <button type="button" class="btn btn-md cleared" onclick="return _Edit_teststep(this)" id="Edit_teststep_btn"><i class="fa-solid fa-pen-to-square"></i></button>
                    {% else %}
                    <button type="button" class="btn btn-md cleared hidden" onclick="return _Edit_teststep(this)" id="Edit_teststep_btn"><i class="fa-solid fa-pen-to-square"></i></button>
                    {% endif %}
                    <button type="button" class="btn btn-sm btn-success hidden" onclick="return _Save_teststep(this)" id="Save_teststep_btn">儲存</button>
                    <button type="button" class="btn btn-sm btn-warning hidden" onclick="return _Cancel_teststep(this)" id="Cancel_teststep_btn">取消</button>
                </span>
                <img src='/static/images/Ellipsis-2.4s-48px.svg' id="loading_save_teststep" class="hidden">
                <a type="button" class="btn" style="float:right" id="fullscreen"><img src='/static/images/fullscreen.svg'></a>
                <a type="button" class="btn hidden" style="float:right" id="smallscreen"><img src='/static/images/fullscreen-exit.svg'></a>
            </h5>
            <button class="fa-solid fa-sort-down dropdown_btn" type="button" data-bs-toggle="collapse" data-bs-target="#Teststep" aria-expanded="true" aria-controls="Teststep"
            aria-label="Teststep" style="border: 0; transform: rotate(0deg);transition:0.5s" id="dropdown_btn3"></button> 
        </p>
        <div class="row g-12 collapse show" id="Teststep">
            {% include "testcase/Testcase_view/test_table.html" %}
        </div>
    </main>
    <br>
    <main>
        <h5>檔案附件
            <span style="width:120px ;">
                {% if creator_bool == True %}
                    <a class="btn btn-primary btn-sm upload_count_class" data-bs-toggle="modal"  href="#file_upload_toggle" role="button"> 上傳文件</a>
                {% else %}
                    <a class="btn btn-primary btn-sm upload_count_class hidden" data-bs-toggle="modal"  href="#file_upload_toggle" role="button"> 上傳文件</a>
                {% endif %}
            </span>
        </h5>
        <button class="fa-solid fa-sort-down dropdown_btn" type="button" data-bs-toggle="collapse" data-bs-target="#five-box-data" aria-expanded="true" aria-controls="five-box-data"
        aria-label="five-box-data" style="border: 0; transform: rotate(0deg);" id="dropdown_btn4"></button> 
        <div class="col-lg-11 mx-auto p-3 py-md-5">
            <div class="row collapse show" id="five-box-data">
                {% include "testcase/Testcase_view/upload_table.html" %}
            </div>
        </div>
        
    </main>
    <main>
        <h5>歷史紀錄</h5>
        <button class="fa-solid fa-sort-down dropdown_btn" type="button" data-bs-toggle="collapse" data-bs-target="#fourth-box-data" aria-expanded="true" aria-controls="fourth-box-data"
        aria-label="fourth-box-data" style="border: 0; transform: rotate(-90deg);" id="dropdown_btn5"></button> 
        <div class="col-lg-11 mx-auto p-3 py-md-5">
            <div class="row g-5 collapse" id="fourth-box-data">
                {% include "testcase/Form_View/history_table.html" %}
            </div>
        </div>
        
    </main>
    <footer class="pt-5 my-5 text-muted border-top">
    </footer>
    </div>
    
    <div class="modal fade" id="file_upload_toggle" aria-hidden="true" aria-labelledby="file_upload_toggleLabel" tabindex="-1">
        {% include "testcase/Testcase_view/file_upload.html" %}
    </div>
    </form>

    
    
    <script src="{% static 'testcase/js/Testcase_view/info.js' %}"></script>
    <script src="{% static 'testcase/js/Testcase_view/context.js' %}"></script>
    <script src="{% static 'testcase/js/Testcase_view/teststep_table.js' %}"></script>
    <script src="{% static 'testcase/js/teststep_show_modal.js' %}"></script>
    <script src="{% static 'testcase/js/teststep_file_upload.js' %}"></script>
    <script src="{% static 'testcase/js/file_upload.js' %}"></script>

{% endblock %}